server:
  port: 9000
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.woniu.fitness.model            # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: item-service-9000
  datasource:
    url: jdbc:mysql://212.64.75.75:3306/cloud_sport?characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                        # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间
  redis:
    #地址
    host: 212.64.75.75
    #端口
    port: 6379
    #索引库
    database: 2
    #密码
    password:
    #超时时间
    timeout: 50000ms

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
